[project]
name = "stakied"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.sip-010-trait]
path = "contracts/traits/sip-010-trait.clar"
epoch = "latest"

[contracts.stakied-sy-token]
path = "contracts/stakied-sy-token.clar"
epoch = "latest"

[contracts.stakied-pt-yt-core]
path = "contracts/stakied-pt-yt-core.clar"
epoch = "latest"

[contracts.stakied-pt-yt-amm]
path = "contracts/stakied-pt-yt-amm.clar"
epoch = "latest"

[contracts.stakied-staking-pool]
path = "contracts/stakied-staking-pool.clar"
epoch = "latest"

[contracts.stakied-fee-vault]
path = "contracts/stakied-fee-vault.clar"
epoch = "latest"

[contracts.stakied-oracle]
path = "contracts/stakied-oracle.clar"
epoch = "latest"

[contracts.stakied-governance]
path = "contracts/stakied-governance.clar"
epoch = "latest"

[contracts.stakied-rewards-distributor]
path = "contracts/stakied-rewards-distributor.clar"
epoch = "latest"

[contracts.stakied-liquidity-gauge]
path = "contracts/stakied-liquidity-gauge.clar"
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
